services:
  node-checker:
    build: .
    container_name: node-checker
    networks:
      br0:
        ipv4_address: 192.168.1.10
    volumes:
      - /mnt/cache/appdata/node-checker:/app/data
    restart: unless-stopped

networks:
  br0:
    name: br0
    external: true
